### ISSUE TITLE
Bug with new Nette Forms probably?

### ISSUE THREAD

**Issue by darkWolf-PR** [IJVo/jQuery-FileUpload#3]
Hi, I´ve upgraded Nette Forms (and contributte/forms-bootstrap) and got this error:

Compile Error
Declaration of Nette\SmartObject::__call(string $name, array $args) must be compatible with Nette\Forms\Controls\BaseControl::__call(string $name, array $args): mixed

After a lot of testing(error message kind of fails to say anything about this component, so I had to add/remove basically everything I have in project), I´ve found the problem is line
`use \Nette\SmartObject;` here:

https://github.com/IJVo/jQuery-FileUpload/blob/944c6ac808729c3a5eb26719c19a5f210b6bd801/src/FileUploadControl.php#L19

Removing it fixes the problem.

Using PHP 8.2 and latest Nette. Not sure, how to make pull request, so using an issue.

**Comment by kropacekt** [comment]
Hi,

bug has been reported here https://github.com/nette/utils/issues/315 and fixed in nette/forms [v3.2.5](https://github.com/nette/forms/releases/tag/v3.2.5).

Now i have this error:
Compile Error

Declaration of Zet\FileUpload\FileUploadControl::getValue() must be compatible with [Nette\Forms\Controls\UploadControl::getValue](phpstorm://open?file=%2Fvar%2Fwww%2Fhtml%2Fvendor%2Fnette%2Fforms%2Fsrc%2FForms%2FControls%2FUploadControl.php&line=79)(): Nette\Http\FileUpload|array|null

**Comment by darkWolf-PR** [comment]
@kropacekt

https://github.com/IJVo/jQuery-FileUpload/blob/944c6ac808729c3a5eb26719c19a5f210b6bd801/src/FileUploadControl.php#L646

This line needs adding return like this:

`public function getValue(): FileUpload|array|null
{ ... }`

(and adding "use Nette\Http\FileUpload;" )

**Comment by kropacekt** [comment]
Should I create the pull request, or will you do it?

**Comment by IJVo** [comment]
Fixed in IJVo/jQuery-FileUpload v3.1.1.
